<?php

namespace AppBundle\Repository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllJoined()
    {
       return $this->getEntityManager()
            ->createQuery(
                'SELECT t, c, a FROM AppBundle:Tache t
                JOIN t.client c
                JOIN t.activite a'
            )
            ->getResult();
    }
}
